### ISSUE TITLE
Seer's UI is not properly scaled on a 4K monitor.

### ISSUE THREAD

**Issue by be5invis** [coooooooooorey/Seer#2]
![](http://ww2.sinaimg.cn/large/798f7769jw1excrgdanp8j20iy0e677m.jpg)

**Comment by coooooooooorey** [comment]
Ok.

我得先找到个机器查查。
周一周二才能知道怎么回事。

thx

**Comment by coooooooooorey** [comment]
发现公司没有 4k 的显示器.........
感觉这个问题得拖一拖了.
:cry:

**Comment by coooooooooorey** [comment]
新地址:
https://github.com/ccseer/Seer

然后高分屏的问题已经解决了...
会在 0.7.0 体现.
Thx
